# Generated by Django 5.1.3 on 2024-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Qualification', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('YOP', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Skills', models.CharField(max_length=10)),
                ('DOB', models.DateField(max_length=20)),
                ('Address', models.CharField(max_length=10)),
                ('Mock_Rating', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=20)),
            ],
        ),
    ]
