# Generated by Django 5.1.3 on 2024-12-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sdata_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='Qualification',
            field=models.CharField(max_length=20),
        ),
    ]
