# Generated by Django 5.1.3 on 2024-12-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sdata_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdata',
            old_name='Company',
            new_name='Department',
        ),
    ]
